#pragma once

const int WIDTH = 800;
const int HEIGHT = 600;

enum ID{PLAYER, ENEMY, BULLET, BORDER, MISC, EXPLOSION};
enum STATE{TITLE, PLAYING, LOST};
namespace KEY {enum KEYS{UP, DOWN, LEFT, RIGHT, SPACE};};
namespace STANCE{enum STANCE {STILL, RUNNING, LADDER, CLIMB, DASH, SHOTING, CHARGING, SPECIAL };};